### PR TITLE
Be less strict about which files exist

### LINKED ISSUE #13: Provide ability to validate base language w/ out comparison
It would be nice if the tool could validate the base language without comparing it to translations to see if there are issues with things like position identifiers within stringsdict files. This would be great as an initial check that things are being properly formatted before being sent to translators, for instance.

### LINKED ISSUE #16: [discovervalues] 'missing' error if a values directory does not contain strings.xml
Hello, first off all let me say how awesome this tool is! I've run it on our iOS project and it works like a charm and since you have Android support, I also really wanted to try it out on our Android project! 

When doing so, I hit the following issue:

```bash
$ locheck discovervalues ~/Code/GitHub/cookpad/global-android/ui-commons/src/main/res --ignore-missing
Error: Files encountered an error at '/Users/.../global-android/ui-commons/src/main/res/values-en-rGB/strings.xml'.
Reason: missing
```

I'm not too familiar with our Android project, but our base **strings.xml** is in the **values** directory, we then have some regional directories for **values-en-rGB** and so on but we don't localise strings for different regions (at least yet) so the **values-en-rGB/strings.xml** doesn't exist. 

Now I figure this is something relatively easy to patch so I'm happy to try and submit a PR, but first i wanted to check with you on the expected behaviour. Is our project configuration common by not having **strings.xml** in every values directory? I guess I see at least three ways to fix this:

1. Ignore the values directory if it doesn't contain **strings.xml**
2. The above, but only when `--ignore-missing` is set? 
3. A different option for passing locales/directories to ignore? 

Let me know your thoughts! Thanks again 🚀

### PR DESCRIPTION
**Pull request by stevelandeyasana**
1. Android `values` directories may omit `strings.xml` if they are not the primary language. (Fix #16)
2. You may pass only one lproj/stringsdict/strings.xml/values file and still have validation happen. (Fix #13)

Incidentally renames `Stringsdict` to `StringsdictFile` to match other types.

### CODE REVIEW

File: Sources/LocheckCommand/main.swift [hunk 1]
```diff
@@ -192,17 +193,24 @@ struct Lproj: ParsableCommand {
...
-        try base.validate(ext: "lproj")
-        try translation.forEach { try $0.validate(ext: "lproj") }
+        try lprojFiles.forEach { try $0.validate(ext: "lproj") }
     }
 
     func run() {
-        print("Validating \(translation.count) lproj files against \(try! Folder(path: base.argument).name)")
+        let baseFile = lprojFiles[0]
+        let translationFiles = lprojFiles.dropFirst()
+        print("Validating \(translationFiles.count) lproj files against \(try! Folder(path: baseFile.argument).name)")
```
Comment (TheDom) [inline Sources/LocheckCommand/main.swift:202]: Consider not printing this if `translationFiles.isEmpty`

File: Sources/LocheckCommand/main.swift [hunk 2]
```diff
@@ -280,6 +283,12 @@ struct DiscoverLproj: ParsableCommand {
             print("Translations to check: \(translationLproj.count)")
```
Comment (TheDom) [inline Sources/LocheckCommand/main.swift:283]: Same, consider not printing this if there are no translations

**Review by TheDom — APPROVED** [review]
LGTM!

File: Sources/LocheckCommand/main.swift (hunk 2 above)
Comment (stevelandeyasana) [reply Sources/LocheckCommand/main.swift:283]: I think this one is OK, I'll change the other one.
