### PR TITLE
Various improvements to support checking Wikipedia's iOS app

### LINKED ISSUE #18: Fails when run on Wikipedia's iOS app
A `try! File(...)` fails.

### PR DESCRIPTION
**Pull request by stevelandeyasana**
This was a really helpful test case because it revealed some bugs in how we read files.

1. `--ignore-warnings` flag. Wikipedia's warnings are all spurious.
2. Stop trying to do a 1:1 mapping of `.strings` files. Instead, combine all strings file values into a single list and compare the lists.
3. Support UTF-16 encoding by retrying file reading if the first read fails with a certain error.
4. Append problem kind to summary lines to make it easier to ignore specific things.
5. File-level errors are now reported in the summary instead of only in the line-by-line stderr errors.
6. Strip common prefix from summary when using `discover*` commands for readability

Example below. The errors aren't really errors for Wikipedia specifically, but I'm not comfortable downgrading them to warnings without a lot more thought, because these errors would really be errors in the Asana app. Looking at the actual strings, it appears they use a custom localization system, so I'm not worried about it.

```
> swift run locheck discoverlproj ~/dev/3p/wikipedia-ios/Wikipedia/iOS\ Native\ Localizations --ignore-warnings
Discovering .lproj files in /Users/stevelandey/dev/3p/wikipedia-ios/Wikipedia/iOS Native Localizations with en as the base
Source of truth: /Users/stevelandey/dev/3p/wikipedia-ios/Wikipedia/iOS Native Localizations/en.lproj/
Translations to check: 108
/Users/stevelandey/dev/3p/wikipedia-ios/Wikipedia/iOS Native Localizations/eu.lproj/Localizable.stringsdict:22: error: 'article-deleted-accessibility-notification' has more arguments than the base language. Extra args: d (stringsdict_entry_has_too_many_arguments)
/Users/stevelandey/dev/3p/wikipedia-ios/Wikipedia/iOS Native Localizations/eu.lproj/Localizable.stringsdict:166: error: 'reading-lists-delete-reading-list-alert-title' has more arguments than the base language. Extra args: d (stringsdict_entry_has_too_many_arguments)
/Users/stevelandey/dev/3p/wikipedia-ios/Wikipedia/iOS Native Localizations/eu.lproj/Localizable.stringsdict:297: error: 'saved-unsave-article-and-remove-from-reading-lists-title' has more arguments than the base language. Extra args: d (stringsdict_entry_has_too_many_arguments)
/Users/stevelandey/dev/3p/wikipedia-ios/Wikipedia/iOS Native Localizations/ga.lproj/Localizable.stringsdict:6: error: 'article-deleted-accessibility-notification' has more arguments than the base language. Extra args: d (stringsdict_entry_has_too_many_arguments)
/Users/stevelandey/dev/3p/wikipedia-ios/Wikipedia/iOS Native Localizations/id.lproj/Localizable.stringsdict:6: error: 'aaald-characters-text-description' has more arguments than the base language. Extra args: d (stringsdict_entry_has_too_many_arguments)
/Users/stevelandey/dev/3p/wikipedia-ios/Wikipedia/iOS Native Localizations/nqo.lproj/Localizable.stringsdict:38: error: 'article-deleted-accessibility-notification' has more arguments than the base language. Extra args: d (stringsdict_entry_has_too_many_arguments)
/Users/stevelandey/dev/3p/wikipedia-ios/Wikipedia/iOS Native Localizations/uk.lproj/Localizable.stringsdict:120: error: 'article-deleted-accessibility-notification' has more arguments than the base language. Extra args: d (stringsdict_entry_has_too_many_arguments)

Summary:
eu.lproj/Localizable.stringsdict
  article-deleted-accessibility-notification:
    ERROR: 'article-deleted-accessibility-notification' has more arguments than the base language. Extra args: d (stringsdict_entry_has_too_many_arguments)
  reading-lists-delete-reading-list-alert-title:
    ERROR: 'reading-lists-delete-reading-list-alert-title' has more arguments than the base language. Extra args: d (stringsdict_entry_has_too_many_arguments)
  saved-unsave-article-and-remove-from-reading-lists-title:
    ERROR: 'saved-unsave-article-and-remove-from-reading-lists-title' has more arguments than the base language. Extra args: d (stringsdict_entry_has_too_many_arguments)
ga.lproj/Localizable.stringsdict
  article-deleted-accessibility-notification:
    ERROR: 'article-deleted-accessibility-notification' has more arguments than the base language. Extra args: d (stringsdict_entry_has_too_many_arguments)
id.lproj/Localizable.stringsdict
  aaald-characters-text-description:
    ERROR: 'aaald-characters-text-description' has more arguments than the base language. Extra args: d (stringsdict_entry_has_too_many_arguments)
nqo.lproj/Localizable.stringsdict
  article-deleted-accessibility-notification:
    ERROR: 'article-deleted-accessibility-notification' has more arguments than the base language. Extra args: d (stringsdict_entry_has_too_many_arguments)
uk.lproj/Localizable.stringsdict
  article-deleted-accessibility-notification:
    ERROR: 'article-deleted-accessibility-notification' has more arguments than the base language. Extra args: d (stringsdict_entry_has_too_many_arguments)
0 warnings, 7 errors
Errors found
```

Fix #18

### CODE REVIEW

File: Sources/LocheckCommand/main.swift [hunk 1]
```diff
@@ -42,43 +42,54 @@ private func withProblemReporter(ignore: [String], _ block: (ProblemReporter) ->
...
         commandName: "xcstrings",
         abstract: "Directly compare .strings files")
 
     @Argument(help: "A list of .strings files, starting with the primary language")
-    private var stringsFiles: [FileArg]
+    private var stringsFiles: [FileArg] = []
 
     @Option(help: ignoreHelpText)
-    private var ignore = [String]()
+    fileprivate var ignore = [String]()
```
Comment (stevelandeyasana) [inline Sources/LocheckCommand/main.swift:72]: I tried and failed to make a superclass for these commands. The only thing I was able to accomplish was to move `ignoreWithShorthand` to a protocol extension, requiring these properties to be fileprivate instead of private.

File: Sources/LocheckLogic/Validators/parseAndValidateXCStrings.swift [hunk 2]
```diff
@@ -12,42 +12,32 @@ import Foundation
...
+    let collectLines = { (files: [File], baseStringMap: [String: FormatString]) -> [LocalizedStringPair] in
+        files.flatMap { file in
+            file.lo_getLines(problemReporter: problemReporter)?
+                .enumerated()
+                .compactMap {
+                    LocalizedStringPair(
+                        string: $0.1,
+                        path: file.path,
+                        line: $0.0 + 1)
+                } ?? []
```
Comment (stevelandeyasana) [inline Sources/LocheckLogic/Validators/parseAndValidateXCStrings.swift:28]: Note that even though strings are combined into a single list per language, each string is still associated with its original file.

File: Sources/LocheckLogic/ProblemReporter.swift [hunk 3]
```diff
@@ -87,13 +96,27 @@ public class ProblemReporter {
...
 
         for path in problemsByFile.keys.sorted() {
-            print(path)
-            let problems = problemsByFile[path]!.map { $0.problem as! SummarizableProblem }
-            let keys = Set(problems.map(\.key))
+            var pathToPrint = path
+            if path.hasPrefix(root) {
+                pathToPrint = String(pathToPrint.dropFirst(root.count))
+            }
+            if path.hasPrefix("/") {
```
Comment (TheDom) [inline Sources/LocheckLogic/ProblemReporter.swift:103]: Should this check `pathToPrint`?

File: Sources/LocheckLogic/Validators/parseAndValidateXCStrings.swift [hunk 4]
```diff
@@ -12,42 +12,32 @@ import Foundation
...
     problemReporter: ProblemReporter) {
-    problemReporter.logInfo("Validating \(translation.path) against \(base.path)")
-
-    let baseStrings = base.lo_lines.enumerated()
-        .compactMap {
-            LocalizedStringPair(
-                string: $0.1,
-                path: base.path,
-                line: $0.0 + 1)
+    let collectLines = { (files: [File], baseStringMap: [String: FormatString]) -> [LocalizedStringPair] in
```
Comment (TheDom) [inline Sources/LocheckLogic/Validators/parseAndValidateXCStrings.swift:19]: Looks like `baseStringMap` is unused?

**Review by TheDom — APPROVED** [review]
LGTM!

File: Sources/LocheckLogic/ProblemReporter.swift (hunk 3 above)
Comment (stevelandeyasana) [reply Sources/LocheckLogic/ProblemReporter.swift]: Yes, fixed

File: Sources/LocheckLogic/Validators/parseAndValidateXCStrings.swift (hunk 4 above)
Comment (stevelandeyasana) [reply Sources/LocheckLogic/Validators/parseAndValidateXCStrings.swift:19]: Hmm, this should have made the tests fail. I'll look into writing a regression test.
